// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessagePackage.proto

package com.pandong.tool.nnts.model;

public final class TransferProto {
  private TransferProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code netty.OperationType}
   */
  public enum OperationType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>HEARTBEAT = 0;</code>
     */
    HEARTBEAT(0),
    /**
     * <code>CONNECT = 1;</code>
     */
    CONNECT(1),
    /**
     * <code>DISCONNECT = 2;</code>
     */
    DISCONNECT(2),
    /**
     * <code>TRANSFER = 3;</code>
     */
    TRANSFER(3),
    /**
     * <code>REGISTER = 4;</code>
     */
    REGISTER(4),
    /**
     * <code>SERVICE_REGISTER = 5;</code>
     */
    SERVICE_REGISTER(5),
    ;

    /**
     * <code>HEARTBEAT = 0;</code>
     */
    public static final int HEARTBEAT_VALUE = 0;
    /**
     * <code>CONNECT = 1;</code>
     */
    public static final int CONNECT_VALUE = 1;
    /**
     * <code>DISCONNECT = 2;</code>
     */
    public static final int DISCONNECT_VALUE = 2;
    /**
     * <code>TRANSFER = 3;</code>
     */
    public static final int TRANSFER_VALUE = 3;
    /**
     * <code>REGISTER = 4;</code>
     */
    public static final int REGISTER_VALUE = 4;
    /**
     * <code>SERVICE_REGISTER = 5;</code>
     */
    public static final int SERVICE_REGISTER_VALUE = 5;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static OperationType valueOf(int value) {
      return forNumber(value);
    }

    public static OperationType forNumber(int value) {
      switch (value) {
        case 0: return HEARTBEAT;
        case 1: return CONNECT;
        case 2: return DISCONNECT;
        case 3: return TRANSFER;
        case 4: return REGISTER;
        case 5: return SERVICE_REGISTER;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<OperationType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        OperationType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<OperationType>() {
            public OperationType findValueByNumber(int number) {
              return OperationType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return TransferProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final OperationType[] VALUES = values();

    public static OperationType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private OperationType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:netty.OperationType)
  }

  public interface TransferOrBuilder extends
      // @@protoc_insertion_point(interface_extends:netty.Transfer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 request_id = 1 [default = 0];</code>
     */
    boolean hasRequestId();
    /**
     * <code>optional int64 request_id = 1 [default = 0];</code>
     */
    long getRequestId();

    /**
     * <code>required int64 client_id = 2;</code>
     */
    boolean hasClientId();
    /**
     * <code>required int64 client_id = 2;</code>
     */
    long getClientId();

    /**
     * <code>optional string service_name = 3;</code>
     */
    boolean hasServiceName();
    /**
     * <code>optional string service_name = 3;</code>
     */
    String getServiceName();
    /**
     * <code>optional string service_name = 3;</code>
     */
    com.google.protobuf.ByteString
        getServiceNameBytes();

    /**
     * <code>required .netty.OperationType operation = 4;</code>
     */
    boolean hasOperation();
    /**
     * <code>required .netty.OperationType operation = 4;</code>
     */
    OperationType getOperation();

    /**
     * <code>optional string signature = 5;</code>
     */
    boolean hasSignature();
    /**
     * <code>optional string signature = 5;</code>
     */
    String getSignature();
    /**
     * <code>optional string signature = 5;</code>
     */
    com.google.protobuf.ByteString
        getSignatureBytes();

    /**
     * <code>map&lt;string, string&gt; header = 6;</code>
     */
    int getHeaderCount();
    /**
     * <code>map&lt;string, string&gt; header = 6;</code>
     */
    boolean containsHeader(
            String key);
    /**
     * Use {@link #getHeaderMap()} instead.
     */
    @Deprecated
    java.util.Map<String, String>
    getHeader();
    /**
     * <code>map&lt;string, string&gt; header = 6;</code>
     */
    java.util.Map<String, String>
    getHeaderMap();
    /**
     * <code>map&lt;string, string&gt; header = 6;</code>
     */

    String getHeaderOrDefault(
            String key,
            String defaultValue);
    /**
     * <code>map&lt;string, string&gt; header = 6;</code>
     */

    String getHeaderOrThrow(
            String key);

    /**
     * <code>map&lt;string, string&gt; cookie = 7;</code>
     */
    int getCookieCount();
    /**
     * <code>map&lt;string, string&gt; cookie = 7;</code>
     */
    boolean containsCookie(
            String key);
    /**
     * Use {@link #getCookieMap()} instead.
     */
    @Deprecated
    java.util.Map<String, String>
    getCookie();
    /**
     * <code>map&lt;string, string&gt; cookie = 7;</code>
     */
    java.util.Map<String, String>
    getCookieMap();
    /**
     * <code>map&lt;string, string&gt; cookie = 7;</code>
     */

    String getCookieOrDefault(
            String key,
            String defaultValue);
    /**
     * <code>map&lt;string, string&gt; cookie = 7;</code>
     */

    String getCookieOrThrow(
            String key);

    /**
     * <code>map&lt;string, string&gt; parameter = 8;</code>
     */
    int getParameterCount();
    /**
     * <code>map&lt;string, string&gt; parameter = 8;</code>
     */
    boolean containsParameter(
            String key);
    /**
     * Use {@link #getParameterMap()} instead.
     */
    @Deprecated
    java.util.Map<String, String>
    getParameter();
    /**
     * <code>map&lt;string, string&gt; parameter = 8;</code>
     */
    java.util.Map<String, String>
    getParameterMap();
    /**
     * <code>map&lt;string, string&gt; parameter = 8;</code>
     */

    String getParameterOrDefault(
            String key,
            String defaultValue);
    /**
     * <code>map&lt;string, string&gt; parameter = 8;</code>
     */

    String getParameterOrThrow(
            String key);

    /**
     * <code>optional bytes data = 9;</code>
     */
    boolean hasData();
    /**
     * <code>optional bytes data = 9;</code>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code netty.Transfer}
   */
  public  static final class Transfer extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:netty.Transfer)
      TransferOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Transfer.newBuilder() to construct.
    private Transfer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Transfer() {
      requestId_ = 0L;
      clientId_ = 0L;
      serviceName_ = "";
      operation_ = 0;
      signature_ = "";
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Transfer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              requestId_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              clientId_ = input.readInt64();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              serviceName_ = bs;
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              OperationType value = OperationType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                bitField0_ |= 0x00000008;
                operation_ = rawValue;
              }
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              signature_ = bs;
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                header_ = com.google.protobuf.MapField.newMapField(
                    HeaderDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000020;
              }
              com.google.protobuf.MapEntry<String, String>
              header__ = input.readMessage(
                  HeaderDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              header_.getMutableMap().put(
                  header__.getKey(), header__.getValue());
              break;
            }
            case 58: {
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
                cookie_ = com.google.protobuf.MapField.newMapField(
                    CookieDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000040;
              }
              com.google.protobuf.MapEntry<String, String>
              cookie__ = input.readMessage(
                  CookieDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              cookie_.getMutableMap().put(
                  cookie__.getKey(), cookie__.getValue());
              break;
            }
            case 66: {
              if (!((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
                parameter_ = com.google.protobuf.MapField.newMapField(
                    ParameterDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000080;
              }
              com.google.protobuf.MapEntry<String, String>
              parameter__ = input.readMessage(
                  ParameterDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              parameter_.getMutableMap().put(
                  parameter__.getKey(), parameter__.getValue());
              break;
            }
            case 74: {
              bitField0_ |= 0x00000020;
              data_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TransferProto.internal_static_netty_Transfer_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 6:
          return internalGetHeader();
        case 7:
          return internalGetCookie();
        case 8:
          return internalGetParameter();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TransferProto.internal_static_netty_Transfer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Transfer.class, Builder.class);
    }

    private int bitField0_;
    public static final int REQUEST_ID_FIELD_NUMBER = 1;
    private long requestId_;
    /**
     * <code>optional int64 request_id = 1 [default = 0];</code>
     */
    public boolean hasRequestId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 request_id = 1 [default = 0];</code>
     */
    public long getRequestId() {
      return requestId_;
    }

    public static final int CLIENT_ID_FIELD_NUMBER = 2;
    private long clientId_;
    /**
     * <code>required int64 client_id = 2;</code>
     */
    public boolean hasClientId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 client_id = 2;</code>
     */
    public long getClientId() {
      return clientId_;
    }

    public static final int SERVICE_NAME_FIELD_NUMBER = 3;
    private volatile Object serviceName_;
    /**
     * <code>optional string service_name = 3;</code>
     */
    public boolean hasServiceName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string service_name = 3;</code>
     */
    public String getServiceName() {
      Object ref = serviceName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          serviceName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string service_name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getServiceNameBytes() {
      Object ref = serviceName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        serviceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OPERATION_FIELD_NUMBER = 4;
    private int operation_;
    /**
     * <code>required .netty.OperationType operation = 4;</code>
     */
    public boolean hasOperation() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required .netty.OperationType operation = 4;</code>
     */
    public OperationType getOperation() {
      OperationType result = OperationType.valueOf(operation_);
      return result == null ? OperationType.HEARTBEAT : result;
    }

    public static final int SIGNATURE_FIELD_NUMBER = 5;
    private volatile Object signature_;
    /**
     * <code>optional string signature = 5;</code>
     */
    public boolean hasSignature() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string signature = 5;</code>
     */
    public String getSignature() {
      Object ref = signature_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          signature_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string signature = 5;</code>
     */
    public com.google.protobuf.ByteString
        getSignatureBytes() {
      Object ref = signature_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        signature_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HEADER_FIELD_NUMBER = 6;
    private static final class HeaderDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          String, String> defaultEntry =
              com.google.protobuf.MapEntry
              .<String, String>newDefaultInstance(
                  TransferProto.internal_static_netty_Transfer_HeaderEntry_descriptor,
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        String, String> header_;
    private com.google.protobuf.MapField<String, String>
    internalGetHeader() {
      if (header_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            HeaderDefaultEntryHolder.defaultEntry);
      }
      return header_;
    }

    public int getHeaderCount() {
      return internalGetHeader().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; header = 6;</code>
     */

    public boolean containsHeader(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      return internalGetHeader().getMap().containsKey(key);
    }
    /**
     * Use {@link #getHeaderMap()} instead.
     */
    @Deprecated
    public java.util.Map<String, String> getHeader() {
      return getHeaderMap();
    }
    /**
     * <code>map&lt;string, string&gt; header = 6;</code>
     */

    public java.util.Map<String, String> getHeaderMap() {
      return internalGetHeader().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; header = 6;</code>
     */

    public String getHeaderOrDefault(
        String key,
        String defaultValue) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, String> map =
          internalGetHeader().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; header = 6;</code>
     */

    public String getHeaderOrThrow(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, String> map =
          internalGetHeader().getMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int COOKIE_FIELD_NUMBER = 7;
    private static final class CookieDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          String, String> defaultEntry =
              com.google.protobuf.MapEntry
              .<String, String>newDefaultInstance(
                  TransferProto.internal_static_netty_Transfer_CookieEntry_descriptor,
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        String, String> cookie_;
    private com.google.protobuf.MapField<String, String>
    internalGetCookie() {
      if (cookie_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            CookieDefaultEntryHolder.defaultEntry);
      }
      return cookie_;
    }

    public int getCookieCount() {
      return internalGetCookie().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; cookie = 7;</code>
     */

    public boolean containsCookie(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      return internalGetCookie().getMap().containsKey(key);
    }
    /**
     * Use {@link #getCookieMap()} instead.
     */
    @Deprecated
    public java.util.Map<String, String> getCookie() {
      return getCookieMap();
    }
    /**
     * <code>map&lt;string, string&gt; cookie = 7;</code>
     */

    public java.util.Map<String, String> getCookieMap() {
      return internalGetCookie().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; cookie = 7;</code>
     */

    public String getCookieOrDefault(
        String key,
        String defaultValue) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, String> map =
          internalGetCookie().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; cookie = 7;</code>
     */

    public String getCookieOrThrow(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, String> map =
          internalGetCookie().getMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int PARAMETER_FIELD_NUMBER = 8;
    private static final class ParameterDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          String, String> defaultEntry =
              com.google.protobuf.MapEntry
              .<String, String>newDefaultInstance(
                  TransferProto.internal_static_netty_Transfer_ParameterEntry_descriptor,
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        String, String> parameter_;
    private com.google.protobuf.MapField<String, String>
    internalGetParameter() {
      if (parameter_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ParameterDefaultEntryHolder.defaultEntry);
      }
      return parameter_;
    }

    public int getParameterCount() {
      return internalGetParameter().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; parameter = 8;</code>
     */

    public boolean containsParameter(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      return internalGetParameter().getMap().containsKey(key);
    }
    /**
     * Use {@link #getParameterMap()} instead.
     */
    @Deprecated
    public java.util.Map<String, String> getParameter() {
      return getParameterMap();
    }
    /**
     * <code>map&lt;string, string&gt; parameter = 8;</code>
     */

    public java.util.Map<String, String> getParameterMap() {
      return internalGetParameter().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; parameter = 8;</code>
     */

    public String getParameterOrDefault(
        String key,
        String defaultValue) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, String> map =
          internalGetParameter().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; parameter = 8;</code>
     */

    public String getParameterOrThrow(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, String> map =
          internalGetParameter().getMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int DATA_FIELD_NUMBER = 9;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>optional bytes data = 9;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional bytes data = 9;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasClientId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOperation()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, requestId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, clientId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, serviceName_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeEnum(4, operation_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, signature_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetHeader(),
          HeaderDefaultEntryHolder.defaultEntry,
          6);
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetCookie(),
          CookieDefaultEntryHolder.defaultEntry,
          7);
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetParameter(),
          ParameterDefaultEntryHolder.defaultEntry,
          8);
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(9, data_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, requestId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, clientId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, serviceName_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, operation_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, signature_);
      }
      for (java.util.Map.Entry<String, String> entry
           : internalGetHeader().getMap().entrySet()) {
        com.google.protobuf.MapEntry<String, String>
        header__ = HeaderDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(6, header__);
      }
      for (java.util.Map.Entry<String, String> entry
           : internalGetCookie().getMap().entrySet()) {
        com.google.protobuf.MapEntry<String, String>
        cookie__ = CookieDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(7, cookie__);
      }
      for (java.util.Map.Entry<String, String> entry
           : internalGetParameter().getMap().entrySet()) {
        com.google.protobuf.MapEntry<String, String>
        parameter__ = ParameterDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(8, parameter__);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Transfer)) {
        return super.equals(obj);
      }
      Transfer other = (Transfer) obj;

      boolean result = true;
      result = result && (hasRequestId() == other.hasRequestId());
      if (hasRequestId()) {
        result = result && (getRequestId()
            == other.getRequestId());
      }
      result = result && (hasClientId() == other.hasClientId());
      if (hasClientId()) {
        result = result && (getClientId()
            == other.getClientId());
      }
      result = result && (hasServiceName() == other.hasServiceName());
      if (hasServiceName()) {
        result = result && getServiceName()
            .equals(other.getServiceName());
      }
      result = result && (hasOperation() == other.hasOperation());
      if (hasOperation()) {
        result = result && operation_ == other.operation_;
      }
      result = result && (hasSignature() == other.hasSignature());
      if (hasSignature()) {
        result = result && getSignature()
            .equals(other.getSignature());
      }
      result = result && internalGetHeader().equals(
          other.internalGetHeader());
      result = result && internalGetCookie().equals(
          other.internalGetCookie());
      result = result && internalGetParameter().equals(
          other.internalGetParameter());
      result = result && (hasData() == other.hasData());
      if (hasData()) {
        result = result && getData()
            .equals(other.getData());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRequestId()) {
        hash = (37 * hash) + REQUEST_ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getRequestId());
      }
      if (hasClientId()) {
        hash = (37 * hash) + CLIENT_ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getClientId());
      }
      if (hasServiceName()) {
        hash = (37 * hash) + SERVICE_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getServiceName().hashCode();
      }
      if (hasOperation()) {
        hash = (37 * hash) + OPERATION_FIELD_NUMBER;
        hash = (53 * hash) + operation_;
      }
      if (hasSignature()) {
        hash = (37 * hash) + SIGNATURE_FIELD_NUMBER;
        hash = (53 * hash) + getSignature().hashCode();
      }
      if (!internalGetHeader().getMap().isEmpty()) {
        hash = (37 * hash) + HEADER_FIELD_NUMBER;
        hash = (53 * hash) + internalGetHeader().hashCode();
      }
      if (!internalGetCookie().getMap().isEmpty()) {
        hash = (37 * hash) + COOKIE_FIELD_NUMBER;
        hash = (53 * hash) + internalGetCookie().hashCode();
      }
      if (!internalGetParameter().getMap().isEmpty()) {
        hash = (37 * hash) + PARAMETER_FIELD_NUMBER;
        hash = (53 * hash) + internalGetParameter().hashCode();
      }
      if (hasData()) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getData().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Transfer parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Transfer parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Transfer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Transfer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Transfer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Transfer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Transfer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Transfer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Transfer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Transfer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Transfer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Transfer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Transfer prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code netty.Transfer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:netty.Transfer)
        TransferOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TransferProto.internal_static_netty_Transfer_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 6:
            return internalGetHeader();
          case 7:
            return internalGetCookie();
          case 8:
            return internalGetParameter();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 6:
            return internalGetMutableHeader();
          case 7:
            return internalGetMutableCookie();
          case 8:
            return internalGetMutableParameter();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TransferProto.internal_static_netty_Transfer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Transfer.class, Builder.class);
      }

      // Construct using com.pandong.tool.nnts.model.TransferProto.Transfer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        requestId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        clientId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        serviceName_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        operation_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        signature_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        internalGetMutableHeader().clear();
        internalGetMutableCookie().clear();
        internalGetMutableParameter().clear();
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return TransferProto.internal_static_netty_Transfer_descriptor;
      }

      public Transfer getDefaultInstanceForType() {
        return Transfer.getDefaultInstance();
      }

      public Transfer build() {
        Transfer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Transfer buildPartial() {
        Transfer result = new Transfer(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.requestId_ = requestId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.clientId_ = clientId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.serviceName_ = serviceName_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.operation_ = operation_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.signature_ = signature_;
        result.header_ = internalGetHeader();
        result.header_.makeImmutable();
        result.cookie_ = internalGetCookie();
        result.cookie_.makeImmutable();
        result.parameter_ = internalGetParameter();
        result.parameter_.makeImmutable();
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000020;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Transfer) {
          return mergeFrom((Transfer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Transfer other) {
        if (other == Transfer.getDefaultInstance()) return this;
        if (other.hasRequestId()) {
          setRequestId(other.getRequestId());
        }
        if (other.hasClientId()) {
          setClientId(other.getClientId());
        }
        if (other.hasServiceName()) {
          bitField0_ |= 0x00000004;
          serviceName_ = other.serviceName_;
          onChanged();
        }
        if (other.hasOperation()) {
          setOperation(other.getOperation());
        }
        if (other.hasSignature()) {
          bitField0_ |= 0x00000010;
          signature_ = other.signature_;
          onChanged();
        }
        internalGetMutableHeader().mergeFrom(
            other.internalGetHeader());
        internalGetMutableCookie().mergeFrom(
            other.internalGetCookie());
        internalGetMutableParameter().mergeFrom(
            other.internalGetParameter());
        if (other.hasData()) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasClientId()) {
          return false;
        }
        if (!hasOperation()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Transfer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Transfer) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long requestId_ ;
      /**
       * <code>optional int64 request_id = 1 [default = 0];</code>
       */
      public boolean hasRequestId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 request_id = 1 [default = 0];</code>
       */
      public long getRequestId() {
        return requestId_;
      }
      /**
       * <code>optional int64 request_id = 1 [default = 0];</code>
       */
      public Builder setRequestId(long value) {
        bitField0_ |= 0x00000001;
        requestId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 request_id = 1 [default = 0];</code>
       */
      public Builder clearRequestId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        requestId_ = 0L;
        onChanged();
        return this;
      }

      private long clientId_ ;
      /**
       * <code>required int64 client_id = 2;</code>
       */
      public boolean hasClientId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 client_id = 2;</code>
       */
      public long getClientId() {
        return clientId_;
      }
      /**
       * <code>required int64 client_id = 2;</code>
       */
      public Builder setClientId(long value) {
        bitField0_ |= 0x00000002;
        clientId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 client_id = 2;</code>
       */
      public Builder clearClientId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        clientId_ = 0L;
        onChanged();
        return this;
      }

      private Object serviceName_ = "";
      /**
       * <code>optional string service_name = 3;</code>
       */
      public boolean hasServiceName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string service_name = 3;</code>
       */
      public String getServiceName() {
        Object ref = serviceName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            serviceName_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string service_name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getServiceNameBytes() {
        Object ref = serviceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          serviceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string service_name = 3;</code>
       */
      public Builder setServiceName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        serviceName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string service_name = 3;</code>
       */
      public Builder clearServiceName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        serviceName_ = getDefaultInstance().getServiceName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string service_name = 3;</code>
       */
      public Builder setServiceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        serviceName_ = value;
        onChanged();
        return this;
      }

      private int operation_ = 0;
      /**
       * <code>required .netty.OperationType operation = 4;</code>
       */
      public boolean hasOperation() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required .netty.OperationType operation = 4;</code>
       */
      public OperationType getOperation() {
        OperationType result = OperationType.valueOf(operation_);
        return result == null ? OperationType.HEARTBEAT : result;
      }
      /**
       * <code>required .netty.OperationType operation = 4;</code>
       */
      public Builder setOperation(OperationType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        operation_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .netty.OperationType operation = 4;</code>
       */
      public Builder clearOperation() {
        bitField0_ = (bitField0_ & ~0x00000008);
        operation_ = 0;
        onChanged();
        return this;
      }

      private Object signature_ = "";
      /**
       * <code>optional string signature = 5;</code>
       */
      public boolean hasSignature() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string signature = 5;</code>
       */
      public String getSignature() {
        Object ref = signature_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            signature_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string signature = 5;</code>
       */
      public com.google.protobuf.ByteString
          getSignatureBytes() {
        Object ref = signature_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          signature_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string signature = 5;</code>
       */
      public Builder setSignature(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        signature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string signature = 5;</code>
       */
      public Builder clearSignature() {
        bitField0_ = (bitField0_ & ~0x00000010);
        signature_ = getDefaultInstance().getSignature();
        onChanged();
        return this;
      }
      /**
       * <code>optional string signature = 5;</code>
       */
      public Builder setSignatureBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        signature_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          String, String> header_;
      private com.google.protobuf.MapField<String, String>
      internalGetHeader() {
        if (header_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              HeaderDefaultEntryHolder.defaultEntry);
        }
        return header_;
      }
      private com.google.protobuf.MapField<String, String>
      internalGetMutableHeader() {
        onChanged();;
        if (header_ == null) {
          header_ = com.google.protobuf.MapField.newMapField(
              HeaderDefaultEntryHolder.defaultEntry);
        }
        if (!header_.isMutable()) {
          header_ = header_.copy();
        }
        return header_;
      }

      public int getHeaderCount() {
        return internalGetHeader().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; header = 6;</code>
       */

      public boolean containsHeader(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        return internalGetHeader().getMap().containsKey(key);
      }
      /**
       * Use {@link #getHeaderMap()} instead.
       */
      @Deprecated
      public java.util.Map<String, String> getHeader() {
        return getHeaderMap();
      }
      /**
       * <code>map&lt;string, string&gt; header = 6;</code>
       */

      public java.util.Map<String, String> getHeaderMap() {
        return internalGetHeader().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; header = 6;</code>
       */

      public String getHeaderOrDefault(
          String key,
          String defaultValue) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, String> map =
            internalGetHeader().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; header = 6;</code>
       */

      public String getHeaderOrThrow(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, String> map =
            internalGetHeader().getMap();
        if (!map.containsKey(key)) {
          throw new IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearHeader() {
        internalGetMutableHeader().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; header = 6;</code>
       */

      public Builder removeHeader(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        internalGetMutableHeader().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @Deprecated
      public java.util.Map<String, String>
      getMutableHeader() {
        return internalGetMutableHeader().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; header = 6;</code>
       */
      public Builder putHeader(
          String key,
          String value) {
        if (key == null) { throw new NullPointerException(); }
        if (value == null) { throw new NullPointerException(); }
        internalGetMutableHeader().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; header = 6;</code>
       */

      public Builder putAllHeader(
          java.util.Map<String, String> values) {
        internalGetMutableHeader().getMutableMap()
            .putAll(values);
        return this;
      }

      private com.google.protobuf.MapField<
          String, String> cookie_;
      private com.google.protobuf.MapField<String, String>
      internalGetCookie() {
        if (cookie_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              CookieDefaultEntryHolder.defaultEntry);
        }
        return cookie_;
      }
      private com.google.protobuf.MapField<String, String>
      internalGetMutableCookie() {
        onChanged();;
        if (cookie_ == null) {
          cookie_ = com.google.protobuf.MapField.newMapField(
              CookieDefaultEntryHolder.defaultEntry);
        }
        if (!cookie_.isMutable()) {
          cookie_ = cookie_.copy();
        }
        return cookie_;
      }

      public int getCookieCount() {
        return internalGetCookie().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; cookie = 7;</code>
       */

      public boolean containsCookie(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        return internalGetCookie().getMap().containsKey(key);
      }
      /**
       * Use {@link #getCookieMap()} instead.
       */
      @Deprecated
      public java.util.Map<String, String> getCookie() {
        return getCookieMap();
      }
      /**
       * <code>map&lt;string, string&gt; cookie = 7;</code>
       */

      public java.util.Map<String, String> getCookieMap() {
        return internalGetCookie().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; cookie = 7;</code>
       */

      public String getCookieOrDefault(
          String key,
          String defaultValue) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, String> map =
            internalGetCookie().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; cookie = 7;</code>
       */

      public String getCookieOrThrow(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, String> map =
            internalGetCookie().getMap();
        if (!map.containsKey(key)) {
          throw new IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearCookie() {
        internalGetMutableCookie().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; cookie = 7;</code>
       */

      public Builder removeCookie(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        internalGetMutableCookie().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @Deprecated
      public java.util.Map<String, String>
      getMutableCookie() {
        return internalGetMutableCookie().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; cookie = 7;</code>
       */
      public Builder putCookie(
          String key,
          String value) {
        if (key == null) { throw new NullPointerException(); }
        if (value == null) { throw new NullPointerException(); }
        internalGetMutableCookie().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; cookie = 7;</code>
       */

      public Builder putAllCookie(
          java.util.Map<String, String> values) {
        internalGetMutableCookie().getMutableMap()
            .putAll(values);
        return this;
      }

      private com.google.protobuf.MapField<
          String, String> parameter_;
      private com.google.protobuf.MapField<String, String>
      internalGetParameter() {
        if (parameter_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              ParameterDefaultEntryHolder.defaultEntry);
        }
        return parameter_;
      }
      private com.google.protobuf.MapField<String, String>
      internalGetMutableParameter() {
        onChanged();;
        if (parameter_ == null) {
          parameter_ = com.google.protobuf.MapField.newMapField(
              ParameterDefaultEntryHolder.defaultEntry);
        }
        if (!parameter_.isMutable()) {
          parameter_ = parameter_.copy();
        }
        return parameter_;
      }

      public int getParameterCount() {
        return internalGetParameter().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; parameter = 8;</code>
       */

      public boolean containsParameter(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        return internalGetParameter().getMap().containsKey(key);
      }
      /**
       * Use {@link #getParameterMap()} instead.
       */
      @Deprecated
      public java.util.Map<String, String> getParameter() {
        return getParameterMap();
      }
      /**
       * <code>map&lt;string, string&gt; parameter = 8;</code>
       */

      public java.util.Map<String, String> getParameterMap() {
        return internalGetParameter().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; parameter = 8;</code>
       */

      public String getParameterOrDefault(
          String key,
          String defaultValue) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, String> map =
            internalGetParameter().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; parameter = 8;</code>
       */

      public String getParameterOrThrow(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, String> map =
            internalGetParameter().getMap();
        if (!map.containsKey(key)) {
          throw new IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearParameter() {
        internalGetMutableParameter().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; parameter = 8;</code>
       */

      public Builder removeParameter(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        internalGetMutableParameter().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @Deprecated
      public java.util.Map<String, String>
      getMutableParameter() {
        return internalGetMutableParameter().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; parameter = 8;</code>
       */
      public Builder putParameter(
          String key,
          String value) {
        if (key == null) { throw new NullPointerException(); }
        if (value == null) { throw new NullPointerException(); }
        internalGetMutableParameter().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; parameter = 8;</code>
       */

      public Builder putAllParameter(
          java.util.Map<String, String> values) {
        internalGetMutableParameter().getMutableMap()
            .putAll(values);
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes data = 9;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional bytes data = 9;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>optional bytes data = 9;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes data = 9;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000100);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:netty.Transfer)
    }

    // @@protoc_insertion_point(class_scope:netty.Transfer)
    private static final Transfer DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Transfer();
    }

    public static Transfer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<Transfer>
        PARSER = new com.google.protobuf.AbstractParser<Transfer>() {
      public Transfer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Transfer(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Transfer> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Transfer> getParserForType() {
      return PARSER;
    }

    public Transfer getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_netty_Transfer_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_netty_Transfer_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_netty_Transfer_HeaderEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_netty_Transfer_HeaderEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_netty_Transfer_CookieEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_netty_Transfer_CookieEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_netty_Transfer_ParameterEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_netty_Transfer_ParameterEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\024MessagePackage.proto\022\005netty\"\261\003\n\010Transf" +
      "er\022\025\n\nrequest_id\030\001 \001(\003:\0010\022\021\n\tclient_id\030\002" +
      " \002(\003\022\024\n\014service_name\030\003 \001(\t\022\'\n\toperation\030" +
      "\004 \002(\0162\024.netty.OperationType\022\021\n\tsignature" +
      "\030\005 \001(\t\022+\n\006header\030\006 \003(\0132\033.netty.Transfer." +
      "HeaderEntry\022+\n\006cookie\030\007 \003(\0132\033.netty.Tran" +
      "sfer.CookieEntry\0221\n\tparameter\030\010 \003(\0132\036.ne" +
      "tty.Transfer.ParameterEntry\022\014\n\004data\030\t \001(" +
      "\014\032-\n\013HeaderEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002" +
      " \001(\t:\0028\001\032-\n\013CookieEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005" +
      "value\030\002 \001(\t:\0028\001\0320\n\016ParameterEntry\022\013\n\003key" +
      "\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001*m\n\rOperationTy" +
      "pe\022\r\n\tHEARTBEAT\020\000\022\013\n\007CONNECT\020\001\022\016\n\nDISCON" +
      "NECT\020\002\022\014\n\010TRANSFER\020\003\022\014\n\010REGISTER\020\004\022\024\n\020SE" +
      "RVICE_REGISTER\020\005B,\n\033com.pandong.tool.nnt" +
      "s.modelB\rTransferProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_netty_Transfer_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_netty_Transfer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_netty_Transfer_descriptor,
        new String[] { "RequestId", "ClientId", "ServiceName", "Operation", "Signature", "Header", "Cookie", "Parameter", "Data", });
    internal_static_netty_Transfer_HeaderEntry_descriptor =
      internal_static_netty_Transfer_descriptor.getNestedTypes().get(0);
    internal_static_netty_Transfer_HeaderEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_netty_Transfer_HeaderEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_netty_Transfer_CookieEntry_descriptor =
      internal_static_netty_Transfer_descriptor.getNestedTypes().get(1);
    internal_static_netty_Transfer_CookieEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_netty_Transfer_CookieEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_netty_Transfer_ParameterEntry_descriptor =
      internal_static_netty_Transfer_descriptor.getNestedTypes().get(2);
    internal_static_netty_Transfer_ParameterEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_netty_Transfer_ParameterEntry_descriptor,
        new String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
